# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9171550c3733e970e8cee74772c2d860d798b1e1046e632ba7fba47d21869805b4618011633196077262c33f4f6085fc9d6c1cf9566ae92bb1a0362bc773cb62

test:
  secret_key_base: 7377b37cfe0038eafe3cbf74c881bd8c145dc3d64cc5c7e746386c48ddd42c623b0dfacdc5c55a89f7a8cce1d599f79d55f31f03f1f6b9ea1116d628557afdb0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
